# Generated by Django 5.1.5 on 2025-01-25 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='agentpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='created_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agentpreferences'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='funding_goal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='bill_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.bill')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
